### PR TITLE
Make it compatible with latest jhipster

### PR DESCRIPTION
**Pull request by tientq**
Make the module compatible with jhipster from 4.6.0 to latest 4.13.3

A test has been excluded. I don't know how to fix this test.
```
    # test/test-dbh.js
    describe('replaceNamingStrategies', function () {
        it('throws when given an unknown build tool', function () {
            assert.throws(() => {
                replaceNamingStrategies('foo');
            }, Error);
        });
    });
```
Travis is green.
Sorry for start from master branch.
Hope this will be merged.

Regards,
Tien Tran

### CODE REVIEW

**Comment by AdrienHorgnies** [comment]
@tientq Thanks for the effort ; I'll have a look at it this weekend.

**Comment by tientq** [comment]
thank you

**Comment by AdrienHorgnies** [comment]
Ok, it seems fine to me, I must only check the broken test with my colleague as I don't understand what it does in the first place.

**Comment by AdrienHorgnies** [comment]
I pulled it locally to be able to merge it into develop.

I'll let Travis checks run and then make a release.

See : #51

**Comment by tientq** [comment]
Thanks

**Pull request closed without merging**
