### PR TITLE
Fix module path

### PR DESCRIPTION
**Pull request by ecostanzi**
Tries to fix compatibility with latest jhipster version. See #53

### CODE REVIEW

**Comment by AdrienHorgnies** [comment]
I just published current version so the way is clear for the version with your PR.

**Comment by AdrienHorgnies** [comment]
Poke me when MR is ready.

**Comment by ecostanzi** [comment]
@AdrienHorgnies For all I know the import problem is fixed now. Tests for version 4.6.2 and 4.13.3 are passing. 
The test failure for the `latest` version seems to be related to the regex applied to the @ManyToMany annotations. Should be fixed in another PR. What do you think?

**Comment by AdrienHorgnies** [comment]
It seems sensible. I'll try to review and merge PR during the week.

**Pull request merged**
